name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign_reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        run: |
          echo '{"reviewers": ["LEI-93794"]}' | gh api \
            repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            --input -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
