name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign_reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: hkusu/review-assign-action@v1.4.0
        with:
          reviewers: LEI-93794
